run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - errcheck
    - gosimple
    - ineffassign
    - typecheck
    - goimports
    - govet
    - staticcheck
    - godot
    - misspell
    - whitespace
    - goconst
    - gocritic
    - nolintlint
    - nakedret
    - forbidigo
    - wsl
    - revive
    - errorlint

issues:
  exclude-use-default: false
  max-issues-per-linter: 0
  max-same-issues: 0
  fix: true
  exclude-dirs:
    - packages/js/
    - packages/go/proto/
    - packages/go/db/
    - node_modules

linters-settings:
  errcheck:
    check-type-assertions: true
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - style
  govet:
    # Enable all analyzers.
    # Default: false
    enable-all: true
    # Disable analyzers by name.
    # Run `go tool vet help` to see all analyzers.
    # Default: []
    disable:
      - fieldalignment # too strict
    # Settings per analyzer.
    settings:
      shadow:
        # Whether to be strict about shadowing; can be noisy.
        # Default: false
        strict: true
  nolintlint:
    require-explanation: true
    require-specific: true
  nakedret:
    # Make an issue if func has more lines of code than this setting, and it has naked returns.
    max-func-lines: 16
  revive:
    rules:
      - name: package-comments
        severity: warning
        disabled: true
output:
  sort-results: true
