// Code generated by "enumer -type=ColumnName -json -transform=snake-upper -output=./columnname.gen.go"; DO NOT EDIT.

package tables

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _ColumnNameName = "COLUMN_NAME_STATUSCOLUMN_NAME_ADDRESSCOLUMN_NAME_PORT_RPCCOLUMN_NAME_TOTAL_TRANSACTIONSCOLUMN_NAME_LATEST_CHECKPOINTCOLUMN_NAME_HIGHEST_CHECKPOINTCOLUMN_NAME_CONNECTED_PEERSCOLUMN_NAME_UPTIMECOLUMN_NAME_VERSIONCOLUMN_NAME_COMMITCOLUMN_NAME_COMPANYCOLUMN_NAME_COUNTRY"

var _ColumnNameIndex = [...]uint16{0, 18, 37, 57, 87, 116, 146, 173, 191, 210, 228, 247, 266}

const _ColumnNameLowerName = "column_name_statuscolumn_name_addresscolumn_name_port_rpccolumn_name_total_transactionscolumn_name_latest_checkpointcolumn_name_highest_checkpointcolumn_name_connected_peerscolumn_name_uptimecolumn_name_versioncolumn_name_commitcolumn_name_companycolumn_name_country"

func (i ColumnName) String() string {
	if i < 0 || i >= ColumnName(len(_ColumnNameIndex)-1) {
		return fmt.Sprintf("ColumnName(%d)", i)
	}
	return _ColumnNameName[_ColumnNameIndex[i]:_ColumnNameIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _ColumnNameNoOp() {
	var x [1]struct{}
	_ = x[ColumnNameStatus-(0)]
	_ = x[ColumnNameAddress-(1)]
	_ = x[ColumnNamePortRPC-(2)]
	_ = x[ColumnNameTotalTransactions-(3)]
	_ = x[ColumnNameLatestCheckpoint-(4)]
	_ = x[ColumnNameHighestCheckpoint-(5)]
	_ = x[ColumnNameConnectedPeers-(6)]
	_ = x[ColumnNameUptime-(7)]
	_ = x[ColumnNameVersion-(8)]
	_ = x[ColumnNameCommit-(9)]
	_ = x[ColumnNameCompany-(10)]
	_ = x[ColumnNameCountry-(11)]
}

var _ColumnNameValues = []ColumnName{ColumnNameStatus, ColumnNameAddress, ColumnNamePortRPC, ColumnNameTotalTransactions, ColumnNameLatestCheckpoint, ColumnNameHighestCheckpoint, ColumnNameConnectedPeers, ColumnNameUptime, ColumnNameVersion, ColumnNameCommit, ColumnNameCompany, ColumnNameCountry}

var _ColumnNameNameToValueMap = map[string]ColumnName{
	_ColumnNameName[0:18]:         ColumnNameStatus,
	_ColumnNameLowerName[0:18]:    ColumnNameStatus,
	_ColumnNameName[18:37]:        ColumnNameAddress,
	_ColumnNameLowerName[18:37]:   ColumnNameAddress,
	_ColumnNameName[37:57]:        ColumnNamePortRPC,
	_ColumnNameLowerName[37:57]:   ColumnNamePortRPC,
	_ColumnNameName[57:87]:        ColumnNameTotalTransactions,
	_ColumnNameLowerName[57:87]:   ColumnNameTotalTransactions,
	_ColumnNameName[87:116]:       ColumnNameLatestCheckpoint,
	_ColumnNameLowerName[87:116]:  ColumnNameLatestCheckpoint,
	_ColumnNameName[116:146]:      ColumnNameHighestCheckpoint,
	_ColumnNameLowerName[116:146]: ColumnNameHighestCheckpoint,
	_ColumnNameName[146:173]:      ColumnNameConnectedPeers,
	_ColumnNameLowerName[146:173]: ColumnNameConnectedPeers,
	_ColumnNameName[173:191]:      ColumnNameUptime,
	_ColumnNameLowerName[173:191]: ColumnNameUptime,
	_ColumnNameName[191:210]:      ColumnNameVersion,
	_ColumnNameLowerName[191:210]: ColumnNameVersion,
	_ColumnNameName[210:228]:      ColumnNameCommit,
	_ColumnNameLowerName[210:228]: ColumnNameCommit,
	_ColumnNameName[228:247]:      ColumnNameCompany,
	_ColumnNameLowerName[228:247]: ColumnNameCompany,
	_ColumnNameName[247:266]:      ColumnNameCountry,
	_ColumnNameLowerName[247:266]: ColumnNameCountry,
}

var _ColumnNameNames = []string{
	_ColumnNameName[0:18],
	_ColumnNameName[18:37],
	_ColumnNameName[37:57],
	_ColumnNameName[57:87],
	_ColumnNameName[87:116],
	_ColumnNameName[116:146],
	_ColumnNameName[146:173],
	_ColumnNameName[173:191],
	_ColumnNameName[191:210],
	_ColumnNameName[210:228],
	_ColumnNameName[228:247],
	_ColumnNameName[247:266],
}

// ColumnNameString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ColumnNameString(s string) (ColumnName, error) {
	if val, ok := _ColumnNameNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _ColumnNameNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to ColumnName values", s)
}

// ColumnNameValues returns all values of the enum
func ColumnNameValues() []ColumnName {
	return _ColumnNameValues
}

// ColumnNameStrings returns a slice of all String values of the enum
func ColumnNameStrings() []string {
	strs := make([]string, len(_ColumnNameNames))
	copy(strs, _ColumnNameNames)
	return strs
}

// IsAColumnName returns "true" if the value is listed in the enum definition. "false" otherwise
func (i ColumnName) IsAColumnName() bool {
	for _, v := range _ColumnNameValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for ColumnName
func (i ColumnName) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for ColumnName
func (i *ColumnName) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("ColumnName should be a string, got %s", data)
	}

	var err error
	*i, err = ColumnNameString(s)
	return err
}
