package enums

//go:generate go run github.com/dmarkham/enumer -type=ActiveValidatorColumnName -json -transform=snake-upper -output=./activevalidatorcolumnname.gen.go
type ActiveValidatorColumnName int

const (
	ActiveValidatorColumnNameName ActiveValidatorColumnName = iota
	ActiveValidatorColumnNameNetAddress
	ActiveValidatorColumnNameVotingPower
	ActiveValidatorColumnNameGasPrice
	ActiveValidatorColumnNameCommissionRate
	ActiveValidatorColumnNameNextEpochStake
	ActiveValidatorColumnNameNextEpochGasPrice
	ActiveValidatorColumnNameNextEpochCommissionRate
	ActiveValidatorColumnNameStakingPoolSuiBalance
	ActiveValidatorColumnNameRewardsPool
	ActiveValidatorColumnNamePoolTokenBalance
	ActiveValidatorColumnNamePendingStake
)
