// Code generated by "enumer -type=PortType -json -transform=snake-upper -output=./porttype.gen.go"; DO NOT EDIT.

package enums

import (
	"encoding/json"
	"fmt"
	"strings"
)

const _PortTypeName = "PORT_TYPE_UNDEFINEDPORT_TYPE_RPCPORT_TYPE_METRICSPORT_TYPE_PEER"

var _PortTypeIndex = [...]uint8{0, 19, 32, 49, 63}

const _PortTypeLowerName = "port_type_undefinedport_type_rpcport_type_metricsport_type_peer"

func (i PortType) String() string {
	if i < 0 || i >= PortType(len(_PortTypeIndex)-1) {
		return fmt.Sprintf("PortType(%d)", i)
	}
	return _PortTypeName[_PortTypeIndex[i]:_PortTypeIndex[i+1]]
}

// An "invalid array index" compiler error signifies that the constant values have changed.
// Re-run the stringer command to generate them again.
func _PortTypeNoOp() {
	var x [1]struct{}
	_ = x[PortTypeUndefined-(0)]
	_ = x[PortTypeRPC-(1)]
	_ = x[PortTypeMetrics-(2)]
	_ = x[PortTypePeer-(3)]
}

var _PortTypeValues = []PortType{PortTypeUndefined, PortTypeRPC, PortTypeMetrics, PortTypePeer}

var _PortTypeNameToValueMap = map[string]PortType{
	_PortTypeName[0:19]:       PortTypeUndefined,
	_PortTypeLowerName[0:19]:  PortTypeUndefined,
	_PortTypeName[19:32]:      PortTypeRPC,
	_PortTypeLowerName[19:32]: PortTypeRPC,
	_PortTypeName[32:49]:      PortTypeMetrics,
	_PortTypeLowerName[32:49]: PortTypeMetrics,
	_PortTypeName[49:63]:      PortTypePeer,
	_PortTypeLowerName[49:63]: PortTypePeer,
}

var _PortTypeNames = []string{
	_PortTypeName[0:19],
	_PortTypeName[19:32],
	_PortTypeName[32:49],
	_PortTypeName[49:63],
}

// PortTypeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func PortTypeString(s string) (PortType, error) {
	if val, ok := _PortTypeNameToValueMap[s]; ok {
		return val, nil
	}

	if val, ok := _PortTypeNameToValueMap[strings.ToLower(s)]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to PortType values", s)
}

// PortTypeValues returns all values of the enum
func PortTypeValues() []PortType {
	return _PortTypeValues
}

// PortTypeStrings returns a slice of all String values of the enum
func PortTypeStrings() []string {
	strs := make([]string, len(_PortTypeNames))
	copy(strs, _PortTypeNames)
	return strs
}

// IsAPortType returns "true" if the value is listed in the enum definition. "false" otherwise
func (i PortType) IsAPortType() bool {
	for _, v := range _PortTypeValues {
		if i == v {
			return true
		}
	}
	return false
}

// MarshalJSON implements the json.Marshaler interface for PortType
func (i PortType) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for PortType
func (i *PortType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("PortType should be a string, got %s", data)
	}

	var err error
	*i, err = PortTypeString(s)
	return err
}
