package columnnames

type ActiveValidatorColumnName int

const (
	ActiveValidatorColumnNameIndex ActiveValidatorColumnName = iota
	ActiveValidatorColumnNameName
	ActiveValidatorColumnNameNetAddress
	ActiveValidatorColumnNameVotingPower
	ActiveValidatorColumnNameGasPrice
	ActiveValidatorColumnNameCommissionRate
	ActiveValidatorColumnNameNextEpochStake
	ActiveValidatorColumnNameNextEpochGasPrice
	ActiveValidatorColumnNameNextEpochCommissionRate
	ActiveValidatorColumnNameStakingPoolSuiBalance
	ActiveValidatorColumnNameRewardsPool
	ActiveValidatorColumnNamePoolTokenBalance
	ActiveValidatorColumnNamePendingStake
)
