package columnnames

type NodeColumnName int

const (
	NodeColumnNameIndex NodeColumnName = iota
	NodeColumnNameHealth
	NodeColumnNameAddress
	NodeColumnNamePortRPC
	NodeColumnNameTotalTransactions
	NodeColumnNameTotalTransactionCertificates
	NodeColumnNameTotalTransactionEffects
	NodeColumnNameLatestCheckpoint
	NodeColumnNameHighestKnownCheckpoint
	NodeColumnNameLastExecutedCheckpoint
	NodeColumnNameHighestSyncedCheckpoint
	NodeColumnNameCheckpointExecBacklog
	NodeColumnNameCheckpointSyncBacklog
	NodeColumnNameCurrentEpoch
	NodeColumnNameTXSyncPercentage
	NodeColumnNameCheckSyncPercentage
	NodeColumnNameNetworkPeers
	NodeColumnNameUptime
	NodeColumnNameVersion
	NodeColumnNameCommit
	NodeColumnNameCountry
)
