package columnnames

type ValidatorColumnName int

const (
	ValidatorColumnNameIndex ValidatorColumnName = iota
	ValidatorColumnNameHealth
	ValidatorColumnNameAddress
	ValidatorColumnNameCurrentEpoch
	ValidatorColumnNameTotalTransactionCertificates
	ValidatorColumnNameTotalTransactionEffects
	ValidatorColumnNameHighestKnownCheckpoint
	ValidatorColumnNameLastExecutedCheckpoint
	ValidatorColumnNameCheckpointExecBacklog
	ValidatorColumnNameHighestSyncedCheckpoint
	ValidatorColumnNameCheckpointSyncBacklog
	ValidatorColumnNameCheckSyncPercentage
	ValidatorColumnNameNetworkPeers
	ValidatorColumnNameUptime
	ValidatorColumnNameVersion
	ValidatorColumnNameCommit
	ValidatorColumnNameCountry
	ValidatorColumnNameCurrentRound
	ValidatorColumnNameHighestProcessedRound
	ValidatorColumnNameLastCommittedRound
	ValidatorColumnNamePrimaryNetworkPeers
	ValidatorColumnNameWorkerNetworkPeers
	ValidatorColumnNameSkippedConsensusTransactions
	ValidatorColumnNameTotalSignatureErrors
)
