# update this section if you want to enable/disable tables
monitors-config:
  rpc-table:
    display: true
  node-table:
    display: true
  peers-table:
    display: true
  system-table:
    display: true
  validators-table:
    display: true

# update this section to add/remove rpc endpoints
public-rpc:
  testnet:
    - "https://wave3-rpc.testnet.sui.io:443"
    - "https://rpc-ws-testnet-w3.suiscan.xyz:443"
    - "https://sui-api.rpcpool.com:443"
    - "https://wave3-rpc.synergynodes.com:443"
  devnet:
    - "https://fullnode.devnet.sui.io"
    - "https://fullnode.devnet.vincagame.com"

# update this section to indicate the location of the configuration file, which can be either fullnode.yaml or validator.yaml
config-path: "/root/.suimon/fullnode.yaml"

full-node:
  json-rpc-address: 0.0.0.0:9000
  metrics-address: 0.0.0.0:9184

validator:
  metrics-address: 0.0.0.0:9184

# update this section to modify the settings related to the network
network:
  name: "testnet"

# provider and country information in tables is requested from https://ipinfo.io/ public API. To use it, you need to obtain an access token on the website,
# which is free and gives you 50k requests per month, which is sufficient for individual usage.
ip-lookup:
  access-token: "55f30ce0213aa7" # temporary access token with requests limit

# update this section to change the visual appearance of the widgets
monitors-visual:
  # set different color schemes for monitor depending on your terminal. Possible values: dark, white, color
  color-scheme: "white"

  # update this section if you want to enable/disable emojis in tables
  enable-emojis: false

# update this section to include details regarding the launch type of the Sui-Node process for the logs to be shown
# fill in only one appropriate value
process-launch-type:
  # name os systemd service, example "suid"
  service-name: ""
  # name of docker image, example "mysten/sui-node"
  docker-image-name: ""
  # name of screen session, example "sui"
  screen-session-name: ""
