package columnnames

type NodeColumnName int

const (
	NodeColumnNameIndex NodeColumnName = iota
	NodeColumnNameHealth
	NodeColumnNameAddress
	NodeColumnNamePortRPC
	NodeColumnNameTotalTransactions
	NodeColumnNameLatestCheckpoint
	NodeColumnNameTotalTransactionCertificates
	NodeColumnNameTotalTransactionEffects
	NodeColumnNameHighestKnownCheckpoint
	NodeColumnNameLastExecutedCheckpoint
	NodeColumnNameCheckpointExecBacklog
	NodeColumnNameHighestSyncedCheckpoint
	NodeColumnNameCheckpointSyncBacklog
	NodeColumnNameCurrentEpoch
	NodeColumnNameTXSyncPercentage
	NodeColumnNameCheckSyncPercentage
	NodeColumnNameNetworkPeers
	NodeColumnNameUptime
	NodeColumnNameVersion
	NodeColumnNameCommit
	NodeColumnNameCountry
)
