package tables

import (
	"github.com/jedib0t/go-pretty/v6/table"
	"github.com/jedib0t/go-pretty/v6/text"

	"github.com/bartosian/sui_helpers/suimon/internal/core/domain/enums/columnnames"
)

var (
	TableStyleValidator      = table.StyleLight
	TableColorsValidator     = text.Colors{text.BgHiGreen, text.FgBlack}
	TableTagValidator        = ""
	TableSortConfigValidator = tableSortConfig{
		{Name: "HEALTH", Mode: table.Dsc},
		{Name: "TOTAL\nTRANSACTIONS", Mode: table.Dsc},
		{Name: "LATEST\nCHECKPOINT", Mode: table.Dsc},
	}
	ColumnsConfigValidator = tableColumnConfig{
		columnnames.ValidatorColumnNameIndex: {
			Name:         "IDX",
			Align:        text.AlignCenter,
			AlignHeader:  text.AlignCenter,
			VAlign:       text.VAlignMiddle,
			VAlignHeader: text.VAlignMiddle,
			Hidden:       false,
		},
		columnnames.ValidatorColumnNameHealth: {
			Name:         "HEALTH",
			Align:        text.AlignCenter,
			AlignHeader:  text.AlignCenter,
			VAlign:       text.VAlignMiddle,
			VAlignHeader: text.VAlignMiddle,
			Hidden:       false,
		},
		columnnames.ValidatorColumnNameAddress: {
			Name:         "ADDRESS",
			Align:        text.AlignCenter,
			AlignHeader:  text.AlignCenter,
			VAlign:       text.VAlignMiddle,
			VAlignHeader: text.VAlignMiddle,
			Hidden:       false,
		},
		columnnames.ValidatorColumnNameTotalTransactionCertificates: {
			Name:         "TOTAL TRANSACTION\nCERTIFICATES",
			Align:        text.AlignCenter,
			AlignHeader:  text.AlignCenter,
			VAlign:       text.VAlignMiddle,
			VAlignHeader: text.VAlignMiddle,
			Hidden:       false,
		},
		columnnames.ValidatorColumnNameTotalTransactionEffects: {
			Name:         "TOTAL TRANSACTION\nEFFECTS",
			Align:        text.AlignCenter,
			AlignHeader:  text.AlignCenter,
			VAlign:       text.VAlignMiddle,
			VAlignHeader: text.VAlignMiddle,
			Hidden:       false,
		},
		columnnames.ValidatorColumnNameHighestKnownCheckpoint: {
			Name:         "HIGHEST KNOWN\nCHECKPOINT",
			Align:        text.AlignCenter,
			AlignHeader:  text.AlignCenter,
			VAlign:       text.VAlignMiddle,
			VAlignHeader: text.VAlignMiddle,
			Hidden:       false,
		},
		columnnames.ValidatorColumnNameHighestSyncedCheckpoint: {
			Name:         "HIGHEST SYNCED\nCHECKPOINT",
			Align:        text.AlignCenter,
			AlignHeader:  text.AlignCenter,
			VAlign:       text.VAlignMiddle,
			VAlignHeader: text.VAlignMiddle,
			Hidden:       false,
		},
		columnnames.ValidatorColumnNameLastExecutedCheckpoint: {
			Name:         "LAST EXECUTED\nCHECKPOINT",
			Align:        text.AlignCenter,
			AlignHeader:  text.AlignCenter,
			VAlign:       text.VAlignMiddle,
			VAlignHeader: text.VAlignMiddle,
			Hidden:       false,
		},
		columnnames.ValidatorColumnNameCheckpointExecBacklog: {
			Name:         "CHECKPOINT EXEC\nBACKLOG",
			Align:        text.AlignCenter,
			AlignHeader:  text.AlignCenter,
			VAlign:       text.VAlignMiddle,
			VAlignHeader: text.VAlignMiddle,
			Hidden:       false,
		},
		columnnames.ValidatorColumnNameCheckpointSyncBacklog: {
			Name:         "CHECKPOINT SYNC\nBACKLOG",
			Align:        text.AlignCenter,
			AlignHeader:  text.AlignCenter,
			VAlign:       text.VAlignMiddle,
			VAlignHeader: text.VAlignMiddle,
			Hidden:       false,
		},
		columnnames.ValidatorColumnNameCurrentEpoch: {
			Name:         "CURRENT\nEPOCH",
			Align:        text.AlignCenter,
			AlignHeader:  text.AlignCenter,
			VAlign:       text.VAlignMiddle,
			VAlignHeader: text.VAlignMiddle,
			Hidden:       false,
		},
		columnnames.ValidatorColumnNameCheckSyncPercentage: {
			Name:         "CHECKPOINTS\nSYNC PERCENTAGE",
			Align:        text.AlignCenter,
			AlignHeader:  text.AlignCenter,
			VAlign:       text.VAlignMiddle,
			VAlignHeader: text.VAlignMiddle,
			Hidden:       false,
		},
		columnnames.ValidatorColumnNameNetworkPeers: {
			Name:         "NETWORK\nPEERS",
			Align:        text.AlignCenter,
			AlignHeader:  text.AlignCenter,
			VAlign:       text.VAlignMiddle,
			VAlignHeader: text.VAlignMiddle,
			Hidden:       false,
		},
		columnnames.ValidatorColumnNameUptime: {
			Name:         "UPTIME DAYS",
			Align:        text.AlignCenter,
			AlignHeader:  text.AlignCenter,
			VAlign:       text.VAlignMiddle,
			VAlignHeader: text.VAlignMiddle,
			Hidden:       false,
		},
		columnnames.ValidatorColumnNameVersion: {
			Name:         "VERSION",
			Align:        text.AlignCenter,
			AlignHeader:  text.AlignCenter,
			VAlign:       text.VAlignMiddle,
			VAlignHeader: text.VAlignMiddle,
			Hidden:       false,
		},
		columnnames.ValidatorColumnNameCommit: {
			Name:         "COMMIT",
			Align:        text.AlignCenter,
			AlignHeader:  text.AlignCenter,
			VAlign:       text.VAlignMiddle,
			VAlignHeader: text.VAlignMiddle,
			Hidden:       false,
		},
		columnnames.ValidatorColumnNameCountry: {
			Name:         "COUNTRY",
			Align:        text.AlignLeft,
			AlignHeader:  text.AlignCenter,
			VAlign:       text.VAlignMiddle,
			VAlignHeader: text.VAlignMiddle,
			Hidden:       false,
		},
		columnnames.ValidatorColumnNameCurrentRound: {
			Name:         "CURRENT ROUND",
			Align:        text.AlignCenter,
			AlignHeader:  text.AlignCenter,
			VAlign:       text.VAlignMiddle,
			VAlignHeader: text.VAlignMiddle,
			Hidden:       false,
		},
		columnnames.ValidatorColumnNameHighestProcessedRound: {
			Name:         "HIGHEST\nPROCESSED ROUND",
			Align:        text.AlignCenter,
			AlignHeader:  text.AlignCenter,
			VAlign:       text.VAlignMiddle,
			VAlignHeader: text.VAlignMiddle,
			Hidden:       false,
		},
		columnnames.ValidatorColumnNameLastCommittedRound: {
			Name:         "LAST\nCOMMITTED ROUND",
			Align:        text.AlignCenter,
			AlignHeader:  text.AlignCenter,
			VAlign:       text.VAlignMiddle,
			VAlignHeader: text.VAlignMiddle,
			Hidden:       false,
		},
		columnnames.ValidatorColumnNamePrimaryNetworkPeers: {
			Name:         "PRIMARY\nNETWORK PEERS",
			Align:        text.AlignCenter,
			AlignHeader:  text.AlignCenter,
			VAlign:       text.VAlignMiddle,
			VAlignHeader: text.VAlignMiddle,
			Hidden:       false,
		},
		columnnames.ValidatorColumnNameWorkerNetworkPeers: {
			Name:         "WORKER\nNETWORK PEERS",
			Align:        text.AlignCenter,
			AlignHeader:  text.AlignCenter,
			VAlign:       text.VAlignMiddle,
			VAlignHeader: text.VAlignMiddle,
			Hidden:       false,
		},
		columnnames.ValidatorColumnNameSkippedConsensusTransactions: {
			Name:         "SKIPPED CONSENSUS\nTRANSACTIONS",
			Align:        text.AlignCenter,
			AlignHeader:  text.AlignCenter,
			VAlign:       text.VAlignMiddle,
			VAlignHeader: text.VAlignMiddle,
			Hidden:       false,
		},
		columnnames.ValidatorColumnNameTotalSignatureErrors: {
			Name:         "TOTAL\nSIGNATURE ERRORS",
			Align:        text.AlignCenter,
			AlignHeader:  text.AlignCenter,
			VAlign:       text.VAlignMiddle,
			VAlignHeader: text.VAlignMiddle,
			Hidden:       false,
		},
	}
	RowsValidator = tableRows{
		0: {
			int(columnnames.ValidatorColumnNameIndex),
			int(columnnames.ValidatorColumnNameHealth),
			int(columnnames.ValidatorColumnNameAddress),
			int(columnnames.ValidatorColumnNameCurrentEpoch),
			int(columnnames.ValidatorColumnNameTotalTransactionCertificates),
			int(columnnames.ValidatorColumnNameTotalTransactionEffects),
			int(columnnames.ValidatorColumnNameHighestKnownCheckpoint),
			int(columnnames.ValidatorColumnNameLastExecutedCheckpoint),
			int(columnnames.ValidatorColumnNameCheckpointExecBacklog),
			int(columnnames.ValidatorColumnNameHighestSyncedCheckpoint),
			int(columnnames.ValidatorColumnNameCheckpointSyncBacklog),
			int(columnnames.ValidatorColumnNameCheckSyncPercentage),
			int(columnnames.ValidatorColumnNameNetworkPeers),
		},
		1: {
			int(columnnames.ValidatorColumnNameUptime),
			int(columnnames.ValidatorColumnNameVersion),
			int(columnnames.ValidatorColumnNameCommit),
			int(columnnames.ValidatorColumnNameCountry),
			int(columnnames.ValidatorColumnNameCurrentRound),
			int(columnnames.ValidatorColumnNameHighestProcessedRound),
			int(columnnames.ValidatorColumnNameLastCommittedRound),
			int(columnnames.ValidatorColumnNamePrimaryNetworkPeers),
			int(columnnames.ValidatorColumnNameWorkerNetworkPeers),
			int(columnnames.ValidatorColumnNameSkippedConsensusTransactions),
			int(columnnames.ValidatorColumnNameTotalSignatureErrors),
		},
	}
)
